export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    genre_ids: [10765, 18, 10759],
    id: 94997,
    origin_country: ["US"],
    original_language: "en",
    original_name: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.",
    popularity: 4123.526,
    poster_path: "/t9XkeE7HzOsdQcDDDapDYh8Rrmt.jpg",
    first_air_date: "2022-08-21",
    name: "House of the Dragon",
    vote_average: 8.426,
    vote_count: 4169,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    backdrop_path: "/qBppESpY8e97WfPWVZiU0JdRXw.jpg",
    id: 84773,
    original_name: "The Lord of the Rings: The Rings of Power",
    overview:
      "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.",
    poster_path: "/mYLOqiStMxDK3fYZFirgrMt8z5d.jpg",
    media_type: "tv",
    adult: false,
    name: "The Lord of the Rings: The Rings of Power",
    original_language: "en",
    genre_ids: [10759, 10765, 18],
    popularity: 211.022,
    first_air_date: "2022-09-01",
    vote_average: 7.3,
    vote_count: 2505,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg",
    id: 83867,
    original_name: "Star Wars: Andor",
    overview:
      "The tale of the burgeoning rebellion against the Empire and how people and planets became involved. In an era filled with danger, deception and intrigue, Cassian Andor embarks on the path that is destined to turn him into a rebel hero.",
    poster_path: "/59SVNwLfoMnZPPB6ukW6dlPxAdI.jpg",
    media_type: "tv",
    adult: false,
    name: "Star Wars: Andor",
    original_language: "en",
    genre_ids: [10765, 10759, 18],
    popularity: 73.886,
    first_air_date: "2022-09-21",
    vote_average: 8.2,
    vote_count: 1093,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
    id: 1399,
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    adult: false,
    name: "Game of Thrones",
    original_language: "en",
    genre_ids: [10765, 18, 10759],
    popularity: 1220.556,
    first_air_date: "2011-04-17",
    vote_average: 8.5,
    vote_count: 23340,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/eljErfkQUcFUgQkI4I1soZcH8MW.jpg",
    id: 92783,
    original_name: "She-Hulk: Attorney at Law",
    overview:
      "Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.",
    poster_path: "/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg",
    media_type: "tv",
    adult: false,
    name: "She-Hulk: Attorney at Law",
    original_language: "en",
    genre_ids: [35, 10765],
    popularity: 77.907,
    first_air_date: "2022-08-18",
    vote_average: 6.274,
    vote_count: 2020,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/14JqSslr0eGIhccIC25UArOIELy.jpg",
    id: 90802,
    original_name: "The Sandman",
    overview:
      "After years of imprisonment, Morpheus — the King of Dreams — embarks on a journey across worlds to find what was stolen from him and restore his power.",
    poster_path: "/q54qEgagGOYCq5D1903eBVMNkbo.jpg",
    media_type: "tv",
    adult: false,
    name: "The Sandman",
    original_language: "en",
    genre_ids: [10765, 18, 10759],
    popularity: 76.177,
    first_air_date: "2022-08-05",
    vote_average: 8.001,
    vote_count: 1933,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    id: 100088,
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    media_type: "tv",
    adult: false,
    name: "The Last of Us",
    original_language: "en",
    genre_ids: [18],
    popularity: 444.557,
    first_air_date: "2023-01-15",
    vote_average: 8.606,
    vote_count: 4830,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/8rK0S1ZWmfF4EqVabdqB9PMIFTS.jpg",
    id: 113988,
    original_name: "DAHMER - Monster: The Jeffrey Dahmer Story",
    overview:
      "This series examines the gruesome and horrific true crimes of Jeffrey Dahmer and the systemic failures that enabled one of America’s most notorious serial killers to continue his murderous spree in plain sight for over a decade.",
    poster_path: "/f2PVrphK0u81ES256lw3oAZuF3x.jpg",
    media_type: "tv",
    adult: false,
    name: "DAHMER - Monster: The Jeffrey Dahmer Story",
    original_language: "en",
    genre_ids: [80, 18],
    popularity: 92.923,
    first_air_date: "2022-09-21",
    vote_average: 8,
    vote_count: 2456,
    origin_country: ["US"],
  },
  {
    backdrop_path: "/s1xnjbOIQtwGObPnydTebp74G2c.jpg",
    id: 90669,
    original_name: "1899",
    overview:
      "Passengers on an immigrant ship traveling to the new continent get caught in a mysterious riddle when they find a second vessel adrift on the open sea.",
    poster_path: "/qmpUDEgZawIlDU5HP3IJ9HjnpI3.jpg",
    media_type: "tv",
    adult: false,
    name: "1899",
    original_language: "de",
    genre_ids: [9648, 18],
    popularity: 50.864,
    first_air_date: "2022-11-17",
    vote_average: 7.565,
    vote_count: 1177,
    origin_country: ["DE"],
  },
  {
    backdrop_path: "/5DUMPBSnHOZsbBv81GFXZXvDpo6.jpg",
    id: 114410,
    original_name: "チェンソーマン",
    overview:
      "Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.",
    poster_path: "/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
    media_type: "tv",
    adult: false,
    name: "Chainsaw Man",
    original_language: "ja",
    genre_ids: [16, 10759, 10765],
    popularity: 397.002,
    first_air_date: "2022-10-12",
    vote_average: 8.559,
    vote_count: 1545,
    origin_country: ["JP"],
  },
  {
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    id: 119051,
    original_name: "Wednesday",
    overview:
      "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    media_type: "tv",
    adult: false,
    name: "Wednesday",
    original_language: "en",
    genre_ids: [10765, 9648, 35],
    popularity: 302.779,
    first_air_date: "2022-11-23",
    vote_average: 8.479,
    vote_count: 8295,
    origin_country: ["US"],
  },
];
